name: Snyk

on:
  push:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Snyk
        run: sudo npm install -g snyk

      - name: Add correct sbt-dependency-graph version
        run: mkdir -p $HOME/.sbt/1.0/plugins && echo 'addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")' >> $HOME/.sbt/1.0/plugins/plugins.sbt

      - name: Run Snyk to check for vulnerabilities
        run: snyk monitor --project-name=snowplow-google-cloud-storage-loader
